# Generated by Django 5.2 on 2025-05-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='amout',
            new_name='amount',
        ),
    ]
