# Generated by Django 5.2 on 2025-05-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_rename_amout_loans_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.RenameModel(
            old_name='Loans',
            new_name='Loan',
        ),
    ]
