# Generated by Django 5.2 on 2025-05-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_rename_cards_card_rename_loans_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountnumber',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
