# Generated by Django 5.2 on 2025-05-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_alter_account_accountnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardnumber',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
